GOAL_POS: []
BOX_POS: []
PLACEMENT_BUFFER_LEN: 3
PLACEMENT_BUFFER_WIDTH: 0
CLOSE_PLACEMENT_DIST: 10
SUCCESS_MARGIN: 0.5
BOX_SIDE: 0.5
NUM_OBSTACLES: 50
OBSTACLE_LEN_RANGE: [0.5, 1, 0.1]
OBSTACLE_WIDTH_RANGE: [0.5, 1, 0.1]
FORWARD_PLACEMENT_DIST: [10, 15]
TYPE: box
BALL_RADIUS: 0.15
BOX_MASS: 1.0