# config/ppo/ppo.yaml
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.2
EPOCHS: 8
BATCH_SIZE: 5120
VALUE_COEF: 0.5
KL_TARGET_COEF: 20.0
USE_CLIP_VALUE_FUNC: True
ENTROPY_COEF: 0.0
TIMESTEPS: 2560
NUM_ENVS: 32
BASE_LR: 3e-4
MIN_LR: 0.0
LR_POLICY: cos
WARMUP_FACTOR: 0.1
WARMUP_ITERS: 5
EPS: 1e-5
MAX_GRAD_NORM: 0.5
MAX_STATE_ACTION_PAIRS: 1e8
MAX_ITERS: ???
VIDEO_LENGTH: 1000
CHECKPOINT_PATH: ""
EARLY_EXIT: False
EARLY_EXIT_STATE_ACTION_PAIRS: 1e8
EARLY_EXIT_MAX_ITERS: ???
