# config/env/env.yaml

FORWARD_REWARD_WEIGHT: 1.0
AVOID_REWARD_WEIGHT: 100.0
CTRL_COST_WEIGHT: 0.0
HEALTHY_REWARD: 0.0
STAND_REWARD_WEIGHT: 0.0
STATE_RANGE: [-100.0, 100.0]
Z_RANGE: [-0.1, !!float .inf]
ANGLE_RANGE: [-0.2, 0.2]
RESET_NOISE_SCALE: 5e-3
STAND_HEIGHT_RATIO: 0.5
MODULES: ["Floor", "Agent"]
WALKER_SUBDIR: "train"
WALKER_DIR: ??? # will be ${UNIMAL_PATH}/${WALKER_SUBDIR}
WALKERS: []
KEYS_TO_KEEP: []
SKIP_SELF_POS: False
TASK: locomotion
WRAPPERS: []
TASK_SAMPLING: balanced_replay_buffer
NEW_SIM_ON_RESET: True

