# config/default.yaml
defaults:
  - XML: default
  - ENV: default
  - TERRAIN: default
  - OBJECT: default
  - HFIELD: default
  - VIDEO: default
  - PPO: default  # todo rename folder to rl?
  - TASK_SAMPLING: default
  - MODEL: default
  - CUDNN: default
  - VECENV: default
#  - _self_

OUT_DIR: ./output
CFG_DEST: config.yaml
ENV_NAME: Unimal-v0
DEVICE: cuda:0
LOG_DEST: stdout
LOG_PERIOD: 10
CHECKPOINT_PERIOD: 100
DATASET_PATH: ./metamorph/dataset
EVAL_PERIOD: -1
NODE_ID: -1
NUM_NODES: 1
UNIMAL_TEMPLATE: ./metamorph/envs/assets/unimal.xml
SAVE_HIST_WEIGHTS: False
DESC: ""
EXIT_ON_MJ_STEP_EXCEPTION: False
MIRROR_DATA_AUG: False

RNG_SEED: 1409
ENV:
  MODULES: ["Agent", "Terrain", "Objects"]
  KEYS_TO_KEEP: ["hfield"]
  TASK: "obstacle"
MODEL:
  TRANSFORMER:
    EXT_HIDDEN_DIMS: [64, 64]
    DECODER_DIMS: [64, 64]
    EXT_MIX: "late"
TERRAIN:
  SIZE: [50, 20, 1]
  START_FLAT: 3
  FLAT_LENGTH_RANGE: [50, 20, 1]
  TYPES: ["flat"]
  BOUNDARY_WALLS: True
HFIELD:
  OBS_SIZE: [1, 4, 4, 4]