SIZE: [25, 20, 1]
START_FLAT: 2
CENTER_FLAT: 2
TYPES: ["gap", "jump"]
FLAT_LENGTH_RANGE: [9, 15, 2]
WALL_LENGTH: 0.1
HFIELD_LENGTH_RANGE: [4, 8, 4]
CURVE_HEIGHT_RANGE: [0.6, 1.2, 0.1]
BOUNDARY_WALLS: True
STEP_HEIGHT: 0.2
STEP_LENGTH_RANGE: [12, 16, 4]
NUM_STEPS: 8
RUGGED_SQUARE_CLIP_RANGE: [0.2, 0.3, 0.1]
BOWL_MAX_Z: 1.3
INCLINE_ANGLE: 0
FLOOR_OFFSET: 0.2